In [10]:
!pip freeze | grep tensorflow

tensorflow==2.8.0
tensorflow-io-gcs-filesystem==0.24.0


In [3]:
!pyenv virtualenvs | grep cassava

  3.8.6/envs/cassava (created from /Users/alecsharp/.pyenv/versions/lewagon)
* cassava (created from /Users/alecsharp/.pyenv/versions/lewagon)


In [3]:
from tensorflow.keras.utils import image_dataset_from_directory

In [ ]:
test_ds = image_dataset_from_directory(
        path,
        image_size=(512, 512),
        shuffle = True
    )

In [4]:
import os
train_path = '../raw_data/cassava-leaf-disease-classification/train_images'

In [7]:
val_ds = image_dataset_from_directory(train_path,
                                          batch_size=32,
                                          subset='validation',
                                          validation_split=.20,
                                          seed=12,
                                          image_size=(512, 512),
                                          shuffle = True)

Found 21397 files belonging to 5 classes.
Using 4279 files for validation.


In [ ]:
#load model 
#predict
#evaluate

In [23]:


for batch in val_ds.take(1).as_numpy_iterator():
    X = batch[0]
    y = batch[1]
    y_pred = eff_model.predict(X)
    np.mean(y_pred, axis = 0)
    print(y_pred.shape, y_pred)
    print(y.shape, y)


(32, 5) [[0.00816948 0.01646689 0.00852636 0.9507653  0.01607193]
 [0.03476623 0.01385942 0.03751004 0.01798626 0.8958781 ]
 [0.04474026 0.46128744 0.03167753 0.390565   0.07172977]
 [0.00691999 0.02497359 0.8892158  0.0216806  0.05720999]
 [0.02804268 0.01787347 0.00451957 0.9258046  0.02375966]
 [0.02777846 0.5496316  0.01464395 0.38672572 0.02122027]
 [0.06305219 0.02492466 0.03267713 0.02226405 0.857082  ]
 [0.00871047 0.03820745 0.2011274  0.72748417 0.02447059]
 [0.00896676 0.01435765 0.01110672 0.95165676 0.01391202]
 [0.00886325 0.01949481 0.00747189 0.9459949  0.01817509]
 [0.01513046 0.05478936 0.00589113 0.90766627 0.01652271]
 [0.08039106 0.8214033  0.02327071 0.03135608 0.04357884]
 [0.16923258 0.61558944 0.01694427 0.04244472 0.15578902]
 [0.5547144  0.33986083 0.03537454 0.01889329 0.05115701]
 [0.00817107 0.02487961 0.43067238 0.50171053 0.03456644]
 [0.03800795 0.87264043 0.01827661 0.03362308 0.03745195]
 [0.04270689 0.85184056 0.02383657 0.02465405 0.05696191]
 [0.00

In [ ]:
from tensorflow.keras.models import load_model

eff_model = load_model('../models/best_model/eff_model')

In [12]:
eff_model.evaluate(val_ds)

In [13]:
# evaluate whole batchs to get error on multiple file uploads